name: Test & publish

# Trigger on push
on:
  push:
    branches:
      - master # master (rerun tests after merging a PR)

jobs:
  # build and run tests
  build:
    runs-on: ubuntu-latest
    # setup node, build, run tests and publish if new release
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install npm packages
        working-directory: ./
        run: npm ci

      - name: Run ESLint
        working-directory: ./
        run: npx eslint ./

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout Github repository
        uses: actions/checkout@v2

      - name: set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install
        working-directory: ./
        run: npm ci

      - name: npm test
        run: npm test
        working-directory: ./

      - name: Create test coverage artifact
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: ./coverage

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout Github repository
        uses: actions/checkout@v1

      - name: set up Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10

      # Publish to npm only if new version
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
